services:
  web:
    build: .
    ports:
      - "${WEB_PORT}:8000"
    volumes:
      - db_data:/data
      - media:/app/media
      - static_data:/app/static

volumes:
  db_data:
  media:
  static_data: