# Generated by Django 4.2.19 on 2025-02-18 09:52

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
