# Generated by Django 4.2.19 on 2025-02-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_alter_documentationpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationpage',
            name='is_root_doc',
            field=models.BooleanField(default=False),
        ),
    ]
